### PR TITLE
Cool idea, fixed it so that your install process works

### PR DESCRIPTION
**Pull request by chbrown**
At least with npm==1.1.65 and node==0.8.14, `npm install` doesn't work.

### CODE REVIEW

**Comment by chbrown** [comment]
$ node stats.js apiengine/github-stats
Using repo: apiengine/github-stats
Average hours: 0.07
Average days: 0

**Comment by thomasdavis** [comment]
Thanks for that, I was thinking of writing it as an npm module and eventually expand with other quick stats you could calculate.

**Comment by thomasdavis** [comment]
lol !

**Comment by thomasdavis** [comment]
lol you have the highest grades I've ever seen

**Comment by thomasdavis** [comment]
@chbrown changed the code to an npm package, so you can pass arguments easier

**Pull request merged**
